/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bill.system;

import javax.swing.JOptionPane;

/**
 *
 * @author Tushar
 */
public class Endingform extends javax.swing.JFrame {

    /**
     * Creates new form Endingform
     */
    public Endingform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        num_malvika = new javax.swing.JLabel();
        num_sakshi = new javax.swing.JLabel();
        num_piyush = new javax.swing.JLabel();
        num_samprit = new javax.swing.JLabel();
        num_deepesh = new javax.swing.JLabel();
        num_keshav = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THIS IS THE END OF OUR PROJECT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        jLabel2.setBackground(new java.awt.Color(255, 102, 102));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("THANKS USER FOR EXPERIENCING OUR SERVICES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("1. Malvika Sinha");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("2. Sakshi Jaiswal");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("3. Piyush Pandey");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("4. Samprit Ganguly");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("6. Keshav Vashist");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("5. Deepesh Baid");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Developed by our group members");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        num_malvika.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        num_malvika.setForeground(new java.awt.Color(255, 255, 255));
        num_malvika.setText("Contact: +919163885060");
        num_malvika.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num_malvika.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num_malvikaMouseClicked(evt);
            }
        });

        num_sakshi.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        num_sakshi.setForeground(new java.awt.Color(255, 255, 255));
        num_sakshi.setText("Contact: +919801212289");
        num_sakshi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num_sakshi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num_sakshiMouseClicked(evt);
            }
        });

        num_piyush.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        num_piyush.setForeground(new java.awt.Color(255, 255, 255));
        num_piyush.setText("Contact: +918240564419");
        num_piyush.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num_piyush.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num_piyushMouseClicked(evt);
            }
        });

        num_samprit.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        num_samprit.setForeground(new java.awt.Color(255, 255, 255));
        num_samprit.setText("Contact: +919674112290");
        num_samprit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num_samprit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num_sampritMouseClicked(evt);
            }
        });

        num_deepesh.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        num_deepesh.setForeground(new java.awt.Color(255, 255, 255));
        num_deepesh.setText("Contact: +918910259536");
        num_deepesh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num_deepesh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num_deepeshMouseClicked(evt);
            }
        });

        num_keshav.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        num_keshav.setForeground(new java.awt.Color(255, 255, 255));
        num_keshav.setText("Contact: +917890234414");
        num_keshav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num_keshav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num_keshavMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(num_malvika)
                    .addComponent(jLabel7)
                    .addComponent(num_samprit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(num_sakshi, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel9))
                    .addComponent(num_deepesh))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num_keshav)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(num_piyush))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_malvika)
                    .addComponent(num_sakshi)
                    .addComponent(num_piyush))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_deepesh)
                    .addComponent(num_samprit)
                    .addComponent(num_keshav))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//PROCESS IS A CLASS BY WHICH WE EXECUTE COMMAND OF CMD VIA JAVA FHILE; 
    private void num_malvikaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num_malvikaMouseClicked
       try {
           Process WhatsApp = Runtime.getRuntime().exec("cmd /c start msedge https://wa.me/919163885060/?text=Hello,%20Malvika%20Sinha%20!&app_absent=1");
       } catch(Exception e){
           JOptionPane.showMessageDialog(this,"Sorry. Can't Communicate at this moment !"); //rehne do teamviewer ko
       }
    }//GEN-LAST:event_num_malvikaMouseClicked

    private void num_sakshiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num_sakshiMouseClicked
        try {
           Process WhatsApp = Runtime.getRuntime().exec("cmd /c start msedge https://wa.me/919801212289/?text=Hello,%20Sakshi%20Jaiswal%20!&app_absent=1");
       } catch(Exception e){
           JOptionPane.showMessageDialog(this,"Sorry. Can't Communicate at this moment !");
       }
    }//GEN-LAST:event_num_sakshiMouseClicked

    private void num_piyushMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num_piyushMouseClicked
        // TODO add your handling code here:
        try{
            Process whatsapp=Runtime.getRuntime().exec("cmd /c start msedge https://wa.me/918240564419/?text=hello,%20Piyush%20Pandey%20!&app absent=1");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Sorry. Can't Communicate at this moment !");
        }
    }//GEN-LAST:event_num_piyushMouseClicked

    private void num_sampritMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num_sampritMouseClicked
        // TODO add your handling code here:
        try{
            Process whatsapp=Runtime.getRuntime().exec("cmd /c start msedge https://wa.me/919674112290/?text=hello,%20Samprit%20Ganguly%20!&app absent=1");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Sorry. Can't Communicate at this moment !");
        }
    }//GEN-LAST:event_num_sampritMouseClicked

    private void num_deepeshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num_deepeshMouseClicked
        // TODO add your handling code here:
        try{
            Process whatsapp=Runtime.getRuntime().exec("cmd /c start msedge https://wa.me/918910259536/?text=hello,%20Samprit%20Ganguly%20!&app absent=1");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Sorry. Can't Communicate at this moment !"); 
        }
    }//GEN-LAST:event_num_deepeshMouseClicked

    private void num_keshavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num_keshavMouseClicked
        // TODO add your handling code here:
        try{
            Process whatsapp=Runtime.getRuntime().exec("cmd /c start msedge https://wa.me/917890234414/?text=hello,%20Samprit%20Ganguly%20!&app absent=1");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Sorry. Can't Communicate at this moment !"); 
        }
    }//GEN-LAST:event_num_keshavMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Endingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Endingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Endingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Endingform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Endingform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel num_deepesh;
    private javax.swing.JLabel num_keshav;
    private javax.swing.JLabel num_malvika;
    private javax.swing.JLabel num_piyush;
    private javax.swing.JLabel num_sakshi;
    private javax.swing.JLabel num_samprit;
    // End of variables declaration//GEN-END:variables
}
