/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bill.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oracle.jdbc.OracleConnection;
import oracle.jdbc.OracleDriver;
import oracle.jdbc.OracleStatement;

/**
 *
 * @author Tushar
 */
public class Unitdetails extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public Unitdetails() {
        initComponents();
        btn_clscr.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vid = new javax.swing.JTextField();
        btn_proceed = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        vunit = new javax.swing.JSpinner();
        button1 = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        vtext = new javax.swing.JTextPane();
        btn_clscr = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enter Consumer ID");
        setLocation(new java.awt.Point(300, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(123, 19, 37));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consumer ID:");

        vid.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vidActionPerformed(evt);
            }
        });

        btn_proceed.setBackground(new java.awt.Color(0, 0, 0));
        btn_proceed.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btn_proceed.setForeground(new java.awt.Color(255, 255, 255));
        btn_proceed.setLabel("Proceed");
        btn_proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proceedActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Units:");

        vunit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        vunit.setModel(new javax.swing.SpinnerNumberModel(15, 15, null, 1));

        button1.setBackground(new java.awt.Color(0, 0, 0));
        button1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("BACK");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        vtext.setEditable(false);
        vtext.setBackground(new java.awt.Color(255, 204, 204));
        vtext.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, null, java.awt.Color.darkGray, java.awt.Color.black));
        vtext.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jScrollPane2.setViewportView(vtext);

        btn_clscr.setBackground(new java.awt.Color(0, 0, 0));
        btn_clscr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_clscr.setForeground(new java.awt.Color(255, 255, 255));
        btn_clscr.setText("Clear ");
        btn_clscr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clscrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_proceed, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vid, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vunit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_clscr, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vunit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(btn_proceed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_clscr)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proceedActionPerformed
         if (vid.getText().equals("") && vunit.getValue().toString().equals("")){
                JOptionPane.showMessageDialog(this,"Please enter valid details");
         }   
          try{
            DriverManager.registerDriver(new OracleDriver());
            OracleConnection ocon = (OracleConnection)DriverManager.getConnection
            ("jdbc:oracle:thin:@LAPTOP-DN033KO9:1521:orcl","MALVIKASINHA","malvi");
            
            OracleStatement osmt = (OracleStatement)ocon.createStatement();//CREATING WAY OF EXECUTING STATEMENTS IN SQL
            String uid=vid.getText();
            String units=vunit.getValue().toString();
    
                if(uid.equals("") ){
                    JOptionPane.showMessageDialog(this,"Please enter a valid ID ");
                }
                else{
                String sql= "update customers_detail set UNITS ='"+units+"' where CONSUMER_ID = '"+uid+"' ";
//                String sq-"select "
                osmt.executeUpdate(sql);
                ocon.commit();
                osmt.close();
                ocon.close();
                JOptionPane.showMessageDialog(this,"USER UPDATED"); 
                int rupee = (Integer.parseInt(units))*10;      
                //TEXTPANE
                vtext.setText(vtext.getText() + " \n ");
                vtext.setText(vtext.getText() + "ELECTRICITY BILL MANAGEMENT SYSTEM");
                vtext.setText(vtext.getText() + " \n ");
                vtext.setText(vtext.getText() + " \n ");
                vtext.setText(vtext.getText() + " \n ");
                vtext.setText(vtext.getText() +"Consumer ID  : " +uid);
                vtext.setText(vtext.getText() + " \n ");
                vtext.setText(vtext.getText() + " \n ");
                vtext.setText(vtext.getText() +"Units Consumed : " +units);
                vtext.setText(vtext.getText() + " \n ");
                vtext.setText(vtext.getText() + " \n ");
                vtext.setText(vtext.getText() +"Amount : " +rupee+ " INR"+"\n");
               
                   btn_clscr.setVisible(true);
                  
                }
          
   
        } 
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,"error");
        }
              
         
//         try {
//             String uname = vid.getText();
//             String units = vunit.getValue().toString();
//             
//             Class.forName("oracle.jdbc.driver.OracleDriver");
//             Connection con=DriverManager.getConnection("jdbc:oracle:thin:@LAPTOP-DN033KO9:1521:orcl","MALVIKASINHA","malvi");
//             Statement st=con.createStatement();
//             st.execute(" update customers_detail set UNITS ='"+units+"' where CONSUMER_ID = '"+uname+"' ");     
////             DriverManager.registerDriver(new OracleDriver());
////             OracleConnection oconn =(OracleConnection)DriverManager.
////             getConnection("jdbc:oracle:thin:@LAPTOP-DN033KO9:1521:orcl","MALVIKASINHA","malvi");
////             OracleStatement ostmt = (OracleStatement)oconn.createStatement();
//             String sql ="update customers_detail set UNITS ='"+units+"' where CONSUMER_ID = '"+uname+"' ";
////             ostmt.executeUpdate(sql);
////             oconn.commit();
////             ostmt.close();
////             oconn.close();
//             if(!uname.equals("")){
//                JOptionPane.showMessageDialog(this, "Units Updated Successfully !");
//                dispose();             
////                Admin_page cv = new Admin_page();
////                cv.dispose();
////                       oconn.commit();
////                        oconn.close();
////                dispose();
//            } else {
//               JOptionPane.showMessageDialog(this, "User does not exist");
//            }
//           
//        }catch (SQLException ex){
//            JOptionPane.showMessageDialog(this,"User does not exist ");
//            vid.grabFocus();
//           } catch (ClassNotFoundException ex) {
//            Logger.getLogger(Unitdetails.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btn_proceedActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        Admin_page ap=new Admin_page();
        ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_button1ActionPerformed

    private void btn_clscrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clscrActionPerformed
        // TODO add your handling code here:
        vtext.setText("");
        btn_clscr.setVisible(false);
    }//GEN-LAST:event_btn_clscrActionPerformed

    private void vidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Unitdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Unitdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Unitdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Unitdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Unitdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clscr;
    private java.awt.Button btn_proceed;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField vid;
    private javax.swing.JTextPane vtext;
    private javax.swing.JSpinner vunit;
    // End of variables declaration//GEN-END:variables
}
